alkemyTech/OT124-CLIENT

- src/components/Footer.js
- Configure footer nav-links and social media buttons.
- Add footer styles to match header styles.
> Footer features updated

- package-lock.json
- src/App.js
- src/components/LoginForm.js
- src/pages/Login.js
- Create login page.
- Create login form with formik and yup validations.
- When available, connect with API.
> Login page - Ot124 24

- src/App.js
- src/components/ContactForm.js
- src/pages/ContactUs.js
> Summary
- Created ContactUs page component
- Added '/contacto' route in App component
- Created and styled ContactForm component
> Created '/contacto' route - OT124 27

- src/components/Header.js
- src/features/authSlice.js
- src/index.js
- src/store.js
- Created and configure redux store
- Created auth slice for delete, set and consume user data in anywhere of the app including with localstorage
- Created handleCloseSesion action in the header component
- Tested all and it works fine
> Created, configure and tested redux auth store  - Ot124 70

- src/pages/News.js
- src/pages/backoffice/news.js
##Summary:
- Connected news list (public and backoffice) with API.
> Connect news list with API - Ot124 58

- src/components/Auth/LoginForm.js
- src/components/Shared/Alerts/ErrorAlert.js
- src/components/Shared/Buttons/GoogleButton.js
- src/components/Shared/Buttons/SendButton.js
- src/pages/Login.js
- Login form refactoring using reusable components.
- Minor Send button component fix.
- Minor Error Alert component fix.
- Created Google Login button component
> Refactoring login

- src/components/UI/Footer.js
- Rearrange footer buttons
- Add link to logo
> Change footer buttons

- src/components/Shared/Buttons/SmallButton.js
- src/components/Shared/Cards/HomeCard.js
- src/components/Testimonials/LastTestimonials.js
- Improve home card component styling
> Home cards

- src/components/Activities/ActivitiesList.js
- src/components/Categories/CategoriesList.js
- src/components/NewsList.js
- src/components/Organizations/OrganizationsList.js
- src/components/Shared/Containers/HeaderList.js
- src/components/Shared/Others/SearchBar.js
- src/components/Shared/Table/BodyTable.js
- src/components/Shared/Table/Pagination.js
- src/features/paginationSlice.js
- src/features/searchSlice.js
- src/hooks/useQueries.js
- src/pages/backoffice/contacts/ContactsLIst.js
- src/pages/backoffice/members/MembersList.js
- src/pages/backoffice/users/BackofficeListUsers.js
- src/services/activities.js
- src/services/categories.js
- src/services/contact.js
- src/services/members.js
- src/services/news.js
- src/services/organization.js
- src/services/testimonials.js
- src/services/users.js
- src/store.js
- Created pagination component and styled
- Created pagination redux slice
- Linked pagination component in backoffice members, users, activities, news, organizations and categories
- Added pagination queries to each getAll services
- Created an useQueries custom hook
- The pagination queries are with this format "?page=n&size=m" where  n>=0 and m=5 by default
- Created search query
- Created SearchBar component and styled
- Created search redux slice
> Created pagination & search features

- src/pages/Activities.js
- Bug fix: page fade in effect on activities
> Fixed activities page fadein effect

- src/components/Members/MemberCard.js
- src/pages/AboutUs.js
- Refactored About Us public page with client info.
- Created Members Cards.
> About Us public page

- package-lock.json
- package.json
- src/components/Contacts/ContacUsDetails.js
- src/components/Contacts/ContactForm.js
- src/components/Shared/Others/Maps.js
- src/pages/ContactUs.js
- yarn.lock
- Installed google maps dependency
- Created maps component
- Updated contactUs page with maps component
> Created Maps component & Added in ContactUs page

- src/components/Activities/ActivitiesList.js
- src/components/Activities/CUActivitiesForm.js
- src/components/Backoffice/BackOfficeAdminLayout.js
- src/components/Backoffice/BackOfficeCard.js
- src/components/Categories/CUCategoriesForm.js
- src/components/Categories/CategoriesList.js
- src/components/Members/CUMembersForm.js
- src/components/News/CUNewsForm.js
- src/components/NewsList.js
- src/components/Organizations/CUOrganizationForm.js
- src/components/Organizations/OrganizationsList.js
- src/components/Shared/Containers/CenterResponsiveContainer.js
- src/components/Shared/Loaders/Spinner.js
- src/components/Shared/Others/NotFoundComponent.js
- src/components/Shared/Table/Pagination.js
- src/components/Testimonials/CUTestimonialsForm.js
- src/components/Testimonials/TestimonialsList.js
- src/components/UI/HeaderUser.js
- src/components/UI/Layout.js
- src/pages/backoffice/contacts/ContactsLIst.js
- src/pages/backoffice/members/MembersList.js
- src/pages/backoffice/users/BackofficeEditUsers.js
- src/pages/backoffice/users/BackofficeListUsers.js
> Created, styled and linked backofficeNavbar & added Spinner to all backoffice routes

- src/components/Members/CUMembersForm.js
- src/pages/backoffice/members/MembersList.js
- Add position field to memebrs list and form.
- Fix edit button.
> Members backoffice issues

- src/components/Organizations/CUOrganizationForm.js
- src/components/Organizations/OrganizationsList.js
- src/components/UI/Footer.js
- src/pages/Home.js
- src/services/index.js
- src/services/organization.js
Complemented with https://github.com/alkemyTech/OT124-SERVER/pull/95
- Fixed backoffice organization form.
- Fixed Footer connections with API.
- Fixed backoffice organization list.
- Connected Home welcome text with API.
- Fixed organization services.
> Organizations Issues

- src/components/Testimonials/LastTestimonials.js
- src/components/Testimonials/TestimonialsCard.js
- Created new testimonials card
> Testimonials cards

- src/components/Shared/Cards/HomeCard.js
- Home news card styling and responsiveness improved.
> Card styling and responsive

- src/components/UI/Header.js
- Close burger menu when a link is clicked.
- Link logo to home page.
> Header fixes

- src/components/Contribuye/Donators.js
> slice donates

- package-lock.json
- src/components/Activities/CUActivitiesForm.js
- src/components/Contribuye/WelcomeMessage.js
- src/components/Members/CUMembersForm.js
- src/components/News/CUNewsForm.js
- src/components/Organizations/CUOrganizationForm.js
- src/components/Profile/ProfileForm.js
- src/components/Shared/Forms/SelectForm.js
- src/components/Shared/Others/UploadImageComponent.js
- src/components/Slides/CUSlidesForm.js
- src/components/Testimonials/CUTestimonialsForm.js
- src/pages/ContactUs.js
- src/pages/backoffice/contacts/ContactsLIst.js
- yarn.lock
Reverts alkemyTech/OT124-CLIENT#130
> Revert "Client development"
